# Generated by Django 4.2.6 on 2023-10-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_usuarios',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('idNomina', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
