# Generated by Django 4.2.6 on 2023-10-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVideo', models.CharField(max_length=50)),
                ('extVideo', models.CharField(max_length=10)),
            ],
        ),
    ]
