# Generated by Django 4.2.6 on 2023-10-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progol', '0002_tbl_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_videos',
            name='idUsuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='progol.tbl_usuarios'),
        ),
    ]
